server:
  port: 8091

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/at-moon/spring-cloud-demo/
          search-paths: config-repo