server:
  port: 8091

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/at-moon/spring-cloud-demo/
          search-paths: config-repo
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"