server:
  port: 8899

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: neo_route
        uri: http://www.ityouknow.com
        predicates:
        - Path=/spring-cloud
      - id: time_route
        uri: http://ityouknow.com
        predicates:
          - Before=2020-07-03T10:45:06+08:00[Asia/Shanghai]
      - id: cookie_route
        uri: http://ityouknow.com
        predicates:
          - Cookie=at, moon
      - id: header_route
        uri: http://ityouknow.com
        predicates:
          - Header=X-Request-Id, \d+
      - id: host_route
        uri: http://ityouknow.com
        predicates:
          - Host=**.atmoon.com
      - id: method_route
        uri: http://ityouknow.com
        predicates:
          - Method=POST
      - id: query_route
        uri: http://www.baidu.com/
        predicates:
          - Query=smile, at.
      - id: remoteaddr_route
        uri: http://ityouknow.com
        predicates:
          - RemoteAddr=127.0.0.1