server:
  port: 8899

spring:
  application:
    name: gateway
  redis:
    host: 192.168.197.128
    port: 6379
    password: mysso
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: retry_test
        uri: lb://demo
        predicates:
        - Path=/girl/hello
        filters:
        - name: Retry
          args:
            retries: 2
            statuses: INTERNAL_SERVER_ERROR
#      - id: hystrix_route
#        uri: lb://DEMO
#        predicates:
#        - Path=/girl/list
#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/error
#      - id: requestratelimiter_route
#        uri: lb://demo
#        filters:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 1
#            key-resolver: "#{@userKeyResolver}"
#        predicates:
#          - Method=GET
#      - id: nameRoot
#        uri: lb://demo
#        predicates:
#        - Path=/demo/**
#        filters:
#        - StripPrefix=1
#        - AddRequestParameter=name, hhh
#      - id: add_request_parameter_route
#        uri: lb://demo
#        filters:
#        - AddRequestParameter=name, hhh
#        predicates:
#          - Method=GET
#      - id: neo_route
#        uri: http://www.ityouknow.com
#        predicates:
#        - Path=/spring-cloud
#      - id: time_route
#        uri: http://ityouknow.com
#        predicates:
#          - Before=2020-07-03T10:45:06+08:00[Asia/Shanghai]
#      - id: cookie_route
#        uri: http://ityouknow.com
#        predicates:
#          - Cookie=at, moon
#      - id: header_route
#        uri: http://ityouknow.com
#        predicates:
#          - Header=X-Request-Id, \d+
#      - id: host_route
#        uri: http://ityouknow.com
#        predicates:
#          - Host=**.atmoon.com
#      - id: method_route
#        uri: http://ityouknow.com
#        predicates:
#          - Method=POST
#      - id: query_route
#        uri: http://www.baidu.com/
#        predicates:
#          - Query=smile, at.
#      - id: remoteaddr_route
#        uri: http://ityouknow.com
#        predicates:
#          - RemoteAddr=127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
