server:
  port: 8888

spring:
  application:
    name: gateway-service-zuul

#zuul:
#  routes:
#    api-test:
#      path: /producer/**
#      serviceId: demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  retryable: true

ribbon:
  # 对当前服务的重试次数
  MaxAutoRetries: 2
  # 切换相同Server的次数
  MaxAutoRetriesNextServer: 0