server:
  port: 8888

spring:
  application:
    name: gateway-service-zuul
  zipkin:
    base-url: http://192.168.197.128:9411/
  sleuth:
    sampler:
      probability: 1.0

#zuul:
#  routes:
#    api-test:
#      path: /producer/**
#      serviceId: demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  retryable: true

ribbon:
  # 对当前服务的重试次数
  MaxAutoRetries: 2
  # 切换相同Server的次数
  MaxAutoRetriesNextServer: 0
